# Title of this configuration file
title: "Camera Test"
# Tag that identifies this configuration file.
tag: "camera_termo-test"
# Description of this configuration file
description: ""
# Author of this configuration file
author: ""

# Extraction rules
rules:
  raw-camera-output:
    plugin: "rbb_tools.plugins.video_extractor"
    config:
      frame_rate: 9
      frame_height: 120
      frame_width: 160
      text_x: 90
      text_y: 5
    topic_matchers:
      - type: "rbb_tools.extraction.matchers.ExactMatchingRule"
        config:
          topics:
            /termal_camera/raw_image: "sensor_msgs/Image"
          remapping:
            /termal_camera/raw_image: "/image"