# Title of this configuration file
title: "Camera Test"
# Tag that identifies this configuration file.
tag: "camera-test"
# Description of this configuration file
description: ""
# Author of this configuration file
author: ""

# Extraction rules
rules:
  raw-camera-output:
    plugin: "rbb_tools.plugins.video_extractor"
    config:
      frame_rate: 30
      frame_height: 480
      frame_width: 640
      text_x: 90
      text_y: 5
    topic_matchers:
      - type: "rbb_tools.extraction.matchers.ExactMatchingRule"
        config:
          topics:
            /d400/color/image_raw/compressed: "sensor_msgs/CompressedImage"
          remapping:
            /d400/color/image_raw/compressed: "/image"
